# Generated by Django 5.1 on 2025-01-26 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GoalBro', '0003_goal_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='category',
            field=models.CharField(choices=[('fitness', 'Fitness 💪'), ('content', 'Content 🎬'), ('finances', 'Finances 💲'), ('skills', 'Skills 🎯'), ('personal', 'Personal 💖'), ('mental', 'Mental 🧠'), ('career', 'Career 💼'), ('other', 'Other ❓')], default='other', max_length=20),
        ),
    ]
