# Generated by Django 5.1 on 2025-01-27 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GoalBro', '0005_alter_update_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='update',
            name='type',
            field=models.CharField(choices=[('increase', 'Increase'), ('decrease', 'Decrease')], default='increase', max_length=10),
        ),
    ]
